---
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  - vhost_alias.load
apache_vhosts:
  - servername: "local"
    extra_parameters: |
     VirtualDocumentRoot /var/www/%-2/web
     <Directory /var/www>
       AllowOverride All
       Options -Indexes +FollowSymLinks
       Require all granted
     </Directory>
     <FilesMatch \.php$>
       SetHandler "proxy:fcgi://127.0.0.1:9000"
     </FilesMatch>

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0.
php_version: "7.1"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php5 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
